# Generated by Django 5.2.7 on 2026-03-26 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feed_production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LarvaeGrowthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('egg', 'Egg'), ('early_instar', 'Early Instar'), ('mid_instar', 'Mid Instar'), ('prepupae', 'Prepupae'), ('pupae', 'Pupae')], max_length=20)),
                ('average_weight_mg', models.DecimalField(decimal_places=3, max_digits=8)),
                ('population_count', models.PositiveIntegerField()),
                ('temperature_celsius', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('humidity_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('observations', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='InputOutputLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('input', 'Input'), ('output', 'Output')], max_length=10)),
                ('material', models.CharField(choices=[('organic_waste', 'Organic Waste'), ('water', 'Water'), ('bsf_larvae', 'BSF Larvae'), ('feed_meal', 'Feed Meal'), ('compost', 'Compost'), ('other', 'Other')], max_length=30)),
                ('quantity_kg', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit_cost_ngn', models.DecimalField(blank=True, decimal_places=2, help_text='Cost in Nigerian Naira', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='io_logs', to='feed_production.feedbatch')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
