# Generated by Django 5.2.7 on 2026-03-26 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feed_production', '0002_initial'),
        ('monitoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inputoutputlog',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='io_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='larvaegrowthrecord',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='larvae_records', to='feed_production.feedbatch'),
        ),
        migrations.AddField(
            model_name='larvaegrowthrecord',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='larvae_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
