# Generated by Django 5.2.7 on 2026-03-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('bsf_larvae_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('organic_waste_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('water_liters', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('additives_description', models.TextField(blank=True)),
                ('feed_produced_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('protein_content_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('moisture_content_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('production_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-production_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=200)),
                ('quantity_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('log_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-log_date'],
            },
        ),
    ]
